name: Security Alerts

on:
  schedule:
    - cron: '0 */3 * * *' # Toutes les 3 heures

jobs:
  security-alerts:
    uses: France-Travail/pass-emploi-tools/.github/workflows/security-alerts.yml@7285f3a11fc6aaa352a5b3aa436adf7ff80f5764
    with:
      repo-name: 'pass-emploi-connect'
    secrets:
      DEPENDABOT_ALERTS_READER: ${{ secrets.DEPENDABOT_ALERTS_READER }}
      MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
